# Generated by Django 4.2.3 on 2023-07-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0002_alter_todoapp_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
