# Generated by Django 4.2.2 on 2023-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0003_alter_todoapp_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'completed')], max_length=100, null=True),
        ),
    ]
