# Generated by Django 4.2.2 on 2023-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0005_alter_todoapp_created_at_alter_todoapp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='priority',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
