# Generated by Django 4.2.2 on 2023-07-17 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todouser', '0006_alter_todoapp_priority_alter_todoapp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='newuser',
        ),
        migrations.AddField(
            model_name='todoapp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Completed', 'Not Completed')], max_length=100, null=True),
        ),
    ]
