# Generated by Django 4.2.2 on 2023-07-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todouser', '0007_remove_todoapp_newuser_todoapp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
