# Generated by Django 4.2.2 on 2023-07-17 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todouser', '0008_alter_todoapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('In Progress', 'In Progress'), ('Not Completed', 'Not Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
