# Generated by Django 4.2.2 on 2023-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0010_alter_todoapp_created_at_alter_todoapp_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='remaining_days',
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In-progress', 'In-progress'), ('Not-completed', 'Not-completed')], max_length=100, null=True),
        ),
    ]
