# Generated by Django 4.2.2 on 2023-07-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0011_remove_todoapp_remaining_days_alter_todoapp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='completion_date',
            field=models.DateField(),
        ),
    ]
