# Generated by Django 4.2.2 on 2023-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todouser', '0012_alter_todoapp_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
